#!/bin/sh

sudo sh /etc/iptables/iptables.sh && sudo iptables-save > /etc/iptables/iptables.rules

cat >> /etc/rc.local << EOF
[ -e /etc/iptables/iptables.rules ] && {
  iptables-restore /etc/iptables/iptables.rules
}
EOF


