#!/bin/sh

# update system
sudo xbps-install -Suy

# install common utils
sudo xbps-install -y rsync curl libcurl-devel wget gcc make cmake git strace neovim screen tmux jq fish-shell at doctl

# self destruct
# sudo ln -s /etc/sv/at /var/service
# read timer < /tmp/explode-timer
# echo "doctl compute droplet delete $(curl -s http://169.254.169.254/metadata/v1/id)" | at now + ${timer:-30 minutes}
