#!/bin/sh

# install utils
xbps-install -y nmap tcpdump termshark tor proxychains-ng john thc-hydra net-snmp python3

# install seclists
git clone https://github.com/danielmiessler/SecLists.git /usr/share/wordlists/seclists


