#!/bin/sh

# update system
sudo xbps-install -y nmap tcpdump termshark tor proxychains john thc-hydra net-snmp python3

sudo mkdir -p /usr/share/wordlists/seclists && {
	sudo git clone https://github.com/danielmiessler/SecLists.git /usr/share/wordlists/seclists.git
}


