#!/bin/sh

sudo xbps-install -Syu xinetd
sudo mkdir -p /srv/xinetd/log
sudo useradd -s /bin/false -d /srv/xinetd
sudo chown xinetd:xinetd -R /srv/xinetd

for d in /tmp/xinetd/*.sh
do
	mv $d /srv/xinetd/$(basename $d).sh
	chmod +x /srv/xinetd/$(basename $d).sh
	read args < /tmp/xinetd/$(basename $d)_args
	cat >> /etc/xinetd.conf <<- .
		service $(basename $d)
		{
			socket_type = stream
			protocol = tcp
			only_from = 0.0.0.0/0 ::/0

			wait = no
			user = xinetd
			group = xinetd
			server = /srv/xinetd/$(basename $d).sh
			server_args = $args
			instances = 50
			nice = 20

			log_type = FILE /srv/xinetd/log/$(basename $d).sh
			log_on_success = PID HOST EXIT DURATION
			log_on_failure = HOST

			disable = no
		}
	.
done
